# Generated by Django 4.2.5 on 2023-09-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
