# Generated by Django 4.2.5 on 2023-09-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0002_alter_classifiedad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='image',
            field=models.ImageField(upload_to='ads'),
        ),
    ]
