# Generated by Django 4.2.5 on 2023-09-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
