# Generated by Django 4.2.5 on 2023-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0003_alter_classifiedad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='bundle_items',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
