# Generated by Django 4.2.5 on 2023-09-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0004_classifiedad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='ad_type',
            field=models.CharField(choices=[('Unitaire', 'Unitaire'), ('Pack', 'Pack')], default='Unitaire', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ads',
            field=models.ManyToManyField(blank=True, related_name='users', to='ads_system.classifiedad'),
        ),
    ]
