# Generated by Django 4.2.5 on 2023-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0004_alter_classifiedad_bundle_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='bundle_items',
            field=models.TextField(blank=True),
        ),
    ]
