# Generated by Django 4.2.5 on 2023-09-10 18:03

import ads_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0005_alter_classifiedad_bundle_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='id',
            field=models.PositiveIntegerField(default=ads_system.models.generate_unique_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
