# Generated by Django 4.2.5 on 2023-09-10 18:05

import ads_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0006_alter_classifiedad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedad',
            name='id',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='ad_id',
            field=models.PositiveIntegerField(default=ads_system.models.generate_unique_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
