# Generated by Django 4.2.5 on 2023-09-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0006_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedad',
            name='bundle_items',
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='bundle_items',
            field=models.ManyToManyField(blank=True, to='ads_system.book'),
        ),
    ]
