# Generated by Django 4.2.5 on 2023-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0007_remove_classifiedad_bundle_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='editeur',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='editeurr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='titre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='classe',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='matiere',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
