# Generated by Django 4.2.5 on 2023-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0007_remove_classifiedad_id_classifiedad_ad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='ad_type',
            field=models.CharField(choices=[('Unitaire', 'Unitaire'), ('Pack', 'Pack')], default='single', max_length=10),
        ),
    ]
