# Generated by Django 4.2.5 on 2023-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0008_remove_book_editeur_remove_book_title_book_editeurr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
    ]
