# Generated by Django 4.2.5 on 2023-09-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0009_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='editeurr',
            new_name='editeur',
        ),
    ]
