# Generated by Django 4.2.5 on 2023-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_system', '0011_book_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedad',
            name='bundle_items',
            field=models.ManyToManyField(blank=True, null=True, to='ads_system.book'),
        ),
    ]
